// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTRKBWPKJlewxqvZs7zgPYOGQVJngGfU',
    appId: '1:68383186020:web:44aef9f96dc79973e51371',
    messagingSenderId: '68383186020',
    projectId: 'flutter-varios-1637a',
    authDomain: 'flutter-varios-1637a.firebaseapp.com',
    databaseURL: 'https://flutter-varios-1637a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-1637a.appspot.com',
    measurementId: 'G-8D6B4TX2LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKF3vYr8Kn-6RQTrhiqc1IcEp1bC8HfWU',
    appId: '1:68383186020:android:e8e465269ae7413ae51371',
    messagingSenderId: '68383186020',
    projectId: 'flutter-varios-1637a',
    databaseURL: 'https://flutter-varios-1637a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-1637a.appspot.com',
  );
}
